#
# This file configures the wallpaper server.
#

# the command executed in order to set a wallpaper on the desktop.
# a single argument which is the file path for it.
SET_WP_CMD = "set_wallpaper.sh"

